#!/bin/bash
# AI-generated installation script for Route Squiggler Render Client systemd service
#
# This script automates the installation of the Route Squiggler systemd service.
# Run it with: sudo bash install-service.sh
#
# NOTE: Run this script with sudo from the Route Squiggler directory

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Route Squiggler Service Installer${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}ERROR: Please run this script with sudo${NC}"
    echo "Usage: sudo bash install-service.sh"
    exit 1
fi

# Get the actual user (not root, but the user who ran sudo)
ACTUAL_USER="${SUDO_USER:-$USER}"
if [ "$ACTUAL_USER" = "root" ]; then
    echo -e "${YELLOW}WARNING: Running as root user. It's recommended to run as a regular user.${NC}"
    read -p "Enter the username that should run the service: " ACTUAL_USER
fi

# Get the current directory (should be Route Squiggler directory)
INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Installation details:"
echo "  User: $ACTUAL_USER"
echo "  Install directory: $INSTALL_DIR"
echo ""

# Check if main.py exists
if [ ! -f "$INSTALL_DIR/main.py" ]; then
    echo -e "${RED}ERROR: main.py not found in current directory!${NC}"
    echo "Please run this script from the Route Squiggler directory."
    exit 1
fi

# Check if Python 3 is installed
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}ERROR: python3 is not installed!${NC}"
    echo "Please install Python 3 first: sudo apt install python3 python3-pip"
    exit 1
fi

echo -e "${GREEN}✓${NC} Python 3 found: $(python3 --version)"

# Check for virtual environment
PYTHON_EXEC="/usr/bin/python3"
if [ -d "$INSTALL_DIR/venv" ]; then
    echo -e "${GREEN}✓${NC} Virtual environment detected at $INSTALL_DIR/venv"
    PYTHON_EXEC="$INSTALL_DIR/venv/bin/python"
elif [ -d "$INSTALL_DIR/.venv" ]; then
    echo -e "${GREEN}✓${NC} Virtual environment detected at $INSTALL_DIR/.venv"
    PYTHON_EXEC="$INSTALL_DIR/.venv/bin/python"
else
    echo -e "${YELLOW}!${NC} No virtual environment found. Using system Python."
    echo "  To create a venv: python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
fi

# Check if requirements are installed
echo ""
echo "Checking Python dependencies"
if $PYTHON_EXEC -c "import PySide6" 2>/dev/null; then
    echo -e "${GREEN}✓${NC} PySide6 is installed"
else
    echo -e "${YELLOW}!${NC} PySide6 not found. Installing dependencies"
    if [ "$PYTHON_EXEC" = "/usr/bin/python3" ]; then
        pip3 install -r "$INSTALL_DIR/requirements.txt"
    else
        $PYTHON_EXEC -m pip install -r "$INSTALL_DIR/requirements.txt"
    fi
fi

# Create the service file
echo ""
echo "Creating systemd service file"
SERVICE_FILE="/etc/systemd/system/route-squiggler.service"

cat > "$SERVICE_FILE" << EOF
# Route Squiggler Render Client - systemd service
# Generated by install-service.sh on $(date)

[Unit]
Description=Route Squiggler Render Client
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$ACTUAL_USER
WorkingDirectory=$INSTALL_DIR

# Environment variables
Environment="PYTHONUNBUFFERED=1"

# Command to run the application
ExecStart=$PYTHON_EXEC main.py nogui

# Log output to output.log in the working directory
# Commented out - using journalctl instead (sudo journalctl -u route-squiggler.service -f)
# StandardOutput=append:$INSTALL_DIR/output.log
# StandardError=append:$INSTALL_DIR/output.log

# Restart policy
Restart=on-failure
RestartSec=10

# Graceful shutdown settings (allow time to finish current job)
TimeoutStopSec=300
KillMode=mixed
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
EOF

echo -e "${GREEN}✓${NC} Service file created at $SERVICE_FILE"

# Set proper permissions on output.log if it doesn't exist
# Commented out - using journalctl instead
# if [ ! -f "$INSTALL_DIR/output.log" ]; then
#     touch "$INSTALL_DIR/output.log"
#     chown "$ACTUAL_USER:$ACTUAL_USER" "$INSTALL_DIR/output.log"
#     echo -e "${GREEN}✓${NC} Created output.log file"
# fi

# Reload systemd
echo ""
echo "Reloading systemd daemon"
systemctl daemon-reload
echo -e "${GREEN}✓${NC} Systemd daemon reloaded"

# Ask if user wants to enable and start the service
echo ""
read -p "Do you want to enable the service to start on boot? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    systemctl enable route-squiggler.service
    echo -e "${GREEN}✓${NC} Service enabled for autostart on boot"
fi

echo ""
read -p "Do you want to start the service now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    systemctl start route-squiggler.service
    echo -e "${GREEN}✓${NC} Service started"
    sleep 2
    
    # Show status
    echo ""
    echo "Current service status:"
    systemctl status route-squiggler.service --no-pager || true
fi

# Print usage instructions
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Installation Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Useful commands:"
echo ""
echo "  Check service status:"
echo "    sudo systemctl status route-squiggler.service"
echo ""
echo "  View live logs (systemd journal):"
echo "    sudo journalctl -u route-squiggler.service -f"
echo ""
echo "  View output.log file (if enabled):"
echo "    tail -f $INSTALL_DIR/output.log"
echo ""
echo "  Start service:"
echo "    sudo systemctl start route-squiggler.service"
echo ""
echo "  Stop service:"
echo "    sudo systemctl stop route-squiggler.service"
echo ""
echo "  Restart service:"
echo "    sudo systemctl restart route-squiggler.service"
echo ""
echo "  Enable autostart on boot:"
echo "    sudo systemctl enable route-squiggler.service"
echo ""
echo "  Disable autostart on boot:"
echo "    sudo systemctl disable route-squiggler.service"
echo ""
echo "  Uninstall service:"
echo "    sudo systemctl stop route-squiggler.service"
echo "    sudo systemctl disable route-squiggler.service"
echo "    sudo rm /etc/systemd/system/route-squiggler.service"
echo "    sudo systemctl daemon-reload"
echo ""
echo -e "${YELLOW}Note:${NC} View logs with: sudo journalctl -u route-squiggler.service -f"
echo ""

